{% set version = "4.8.6" %}
{% set name = "libgap" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://files.sagemath.org/spkg/upstream/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbd89bff4b2a03a0fd52451ebd6bea1e2742a5f0f4503c50e1a7a05254e9aec0
  patches:
    # https://github.com/gap-system/gap/pull/448
    - patches/448.patch
    # https://github.com/gap-system/gap/pull/1188
    - patches/long_path.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('c') }}
  host:
    - gap {{ version }}
    - gmp
    - mpfr
  run:
    - gap {{ version }}
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/gap/gap.h
    - test -f ${PREFIX}/lib/libgap.a
    - test -f ${PREFIX}/lib/libgap.dylib     # [osx]
    - test -f ${PREFIX}/lib/libgap.so        # [linux]

about:
  home: https://bitbucket.org/vbraun/libgap
  license: GPLv3+
  license_file: COPYING
  summary: A C library version of the GAP kernel.
  dev_url: https://bitbucket.org/vbraun/libgap

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
