travis:
  secure:
    BINSTAR_TOKEN: rQs2nmH8+Qtwn6LsZG8kzLklQ7xbt7HBFrGBV8dngzfx1ZSsjXaxM+s/f1zKfuUla349b0WxmJ4LDaV1Rb/9LTjEb1ro2sZBFvdMennFhNg624Ab8gD7w1tJYHj8gzHk5V/ANIfEexxZw6kycfqdguuax/pYCUq1aoSZ8f0grIX+JDpk4qlNIHhhw+1NFkGN0CCbCe4bomORtSEugY/uWvNxH40xmjVn8xugoOShIEhFNfLmwNN/14bTWe/oFOrnZzqTP5AEerd6HD1oGZLkVSUCbg2Eyqh4fRsxOQmCucL5JyGiWGwasOIVPXwqikDxzubudgzZgA65n9zy5PBT1GwzzPUdldfyntGAZhCh2HOztZX6w6kYRk6MqMGn1u1tbGHu4foLdhVo+k3nNlJMlfP1vgB3jdRsVPkkLK/amPKCfsw1PGhKEfrOfv0iMUPJXjz9hEdze1nNhFxfb6exvJlyHwFYBty8YGmxbEt0iv8KGga81CJGNRK2sxNn5tbD8adHeZjIRCW/SYXbLbBSG8W8qRlTckCDMbGIc+0UUscxIHft3oTJU8Nyw9wNu4tsoB+JpCR4GbMpqXNCWKZNQ+rUKwiqj9KTXjZXfbAn32CptQLYauVDpMxs85hAKFdhn7fKlekIeGWgb9mU+DV2L4u8DDj7pHESNdRwrsbgXCM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
